### ISSUE TITLE
Provide option to raise socket child freezeLimit

### ISSUE THREAD

**Issue by Lange** [nrkno/tv-automation-atem-connection#75]
* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
On low-powered devices such as the Tessel 2, the default freezeLimit of 200ms is too aggressive, and causes the startup sequence to fail.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
It seems to take about 15 seconds to complete the initial socket creation and handshakes, but after that it is fine and seems to run relatively normally. That itself might be indicative of a bug.

**Comment by Julusian** [comment]
Perhaps instead of letting the user adjust this, it would be better to have it a bit higher anyway, and minimise the amount the child code will be blocking so that the pings have a chance of being reposnded to.
For example, the parsing code will be parsing every command in a packet before handling other calls from the parent

**Comment by Lange** [comment]
I agree that avoiding the need to have users adjust this in the first place is ideal.

**Comment by Julusian** [comment]
hmm.. the child process is not parsing the commands, so I dont know what could be being so slow with it. perhaps it is the data transfers in and out of the child?

**Comment by Julusian** [comment]
Implemented in https://github.com/nrkno/tv-automation-atem-connection/commit/724d5aaa142f23afc62f5ee53d572501a541cfa4

From some digging, if the parent process blocks for a certain period then the child will see that as a timeout and shutdown. So either side blocking for longer will cause the connection to die, which could be your problem here

**Comment by Julusian** [comment]
The child process no longer relies on parent pings to do a liveness check, so this should be fully resolved in the `2.0.0-nightly-20200626-195656-eb05a5c.0` prerelease
